all:
#	gcc -g -std=c99 -o usbtiny_osx usbtiny_osx.m -framework Foundation -framework IOKit
	gcc -g -std=c99 -o reset_usb reset_usb.m -framework Foundation -framework IOKit

clean:
#	rm -rf usbtiny_osx
	rm -rf reset_usb
